src/main/java/com/samcomo/dbz/report/controller/ReportController.java, src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java, src/main/java/com/samcomo/dbz/report/service/ReportService.java, src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
<br/>
코드 리뷰에서 받은 피드백을 참고하여 코드를 수정했습니다!
- 수정 후 저장하지 않아 발생한 문제여서 save() 메소드를 사용하여 수정된 Report 를 저장하였습니다.
> 와일드 카드 삭제
- 와일드 카드를 사용하여 Response 객체를 표시한 부분을 모두 실제 반환 객체로 바꿨습니다.
- 기존에는 게스글을 저장하고 s3 버킷에 객체를 저장하는 순서로 로직이 동작했습니다.
- 수정 후 s3 버킷에 객체를 먼저 저장하고 게시글을 저장하는 순서로 로직 수정하였습니다. 
- s3 객체에 이미지를 업로드 중 에러가 발생할 경우 롤백하기 위해 트랜잭션을 사용하였지만 s3 객체를 먼저 저장하게 되면서 에러가 발생하면 게시글 저장도 발생하지 않아 트랜잭션을 사용하지 않을 수 있습니다.
<br/>
- 트랜잭션을 사용하면 데이터베이스의 원자성과 무결성을 보장할 수 있지만 비용이 발생합니다. 하지만 트랜잭션을 관리하며 오버헤드가 발생할 수 있고 **동시성이 높은 환경에서는 트랜잭션 충돌이 발생**할 수 있습니다. 또한 긴시간 동안 트랜잭션이 동작하면 **데이터베이스의 리소스를 오랫동안 점유하게되어 성능문제가 발생**할 수 있습니다.
- 그래서 사용하지 않을 수 있다면 사용않하는게 좋을것이라 판단하였습니다.
- uploadReport() 메소드에서 save(), saveAll() 메소드 사용을 고민했습니다. 현재 상황에서는 큰차이가 없지만 많은 데이터를 저장해야할 수도 있다고 생각해서 saveAll() 메소드를 선택했습니다.
- 트랜잭션이 상위 트랜잭션에 참여하게 되는 특성으로 인해 많은 데이터를 한번에 저장할 …
=> refactor : 피드백 반영한 코드 수정

src/main/java/com/samcomo/dbz/DbzApplication.java, src/main/java/com/samcomo/dbz/global/entity/BaseEntity.java, src/main/java/com/samcomo/dbz/member/model/entity/Member.java
close #17 
<br/>
BaseEntity 는 다양한 엔티티의 공통 필드를 담고있는 클래스입니다. 공통 필드의 예시는 생성일자, 수정일자 등이 있습니다.
BaseEntity 를 상속받은 엔티티는 따로 수정하거나 초기화하지 않아도 자동으로 해당 필드의 값이 저장됩니다.
이때 중요한 것은 상속관계의 엔티티의 관계에 초점을 맞추어 어노테이션의 역할, 어노테이션 끼리의 충돌, 어떤 어노테이션이 적합한지 등을 알고 사용해야 합니다.
아래는 제가 제안하는 방식입니다. 다른 의견 혹은 좋은 아이디어가 언제든 환영입니다!
<br/>
[@EnableJpaAuditing 추가]
> BaseEntity 를 상속받은 엔티티의 생성일자와 수정일자가 자동으로 반영되도록 하는 어노테이션을 추가했습니다.
<br/>
[BaseEntity : abstract 클래스로 변경]
> BaseEntity 는 직접 객체를 생성하여 사용하지 않으므로 abstract 클래스로 선언하여 상속하도록 강제했습니다.
<br/>
[부모, 자식 엔티티의 어노테이션 구성 변경]
> 이슈에 상세히 적었습니다. 구현된 코드와 함께 봐주세요!
<br/>
[네이밍 변경]
> imageUrl 은 다소 명확하지 않은 부분이 있어 profileImageUrl 로 변경하는 것을 제안합니다.
>
> user 가 사용된 부분은 member 로 변경했습니다.
<br/>
회원가입 구현 로직과 일부 섞여 혼란드려 죄송합니다..! 마지막 줄에 비밀번호 인코딩하는 부분은 다음 pr 때 참고해주세요..ㅎㅎ
=> [#17]refactor: baseEntity 설정 변경

build.gradle, src/main/java/com/samcomo/dbz/DbzApplication.java, src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java, src/main/java/com/samcomo/dbz/global/entity/BaseEntity.java, src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java, src/main/java/com/samcomo/dbz/member/controller/MemberController.java, src/main/java/com/samcomo/dbz/member/model/constants/MemberRole.java, src/main/java/com/samcomo/dbz/member/model/constants/SocialType.java, src/main/java/com/samcomo/dbz/member/model/constants/UserRole.java, src/main/java/com/samcomo/dbz/member/model/dto/RegisterDto.java, src/main/java/com/samcomo/dbz/member/model/entity/Member.java, src/main/java/com/samcomo/dbz/member/model/repository/MemberRepository.java, src/main/java/com/samcomo/dbz/member/service/MemberService.java, src/main/java/com/samcomo/dbz/member/service/impl/MemberServiceImpl.java, src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java, src/test/java/com/samcomo/dbz/member/service/impl/MemberServiceImplTest.java
close #16 
<br/>
[전체 플로우]
클라이언트가 회원가입에 필요한 정보와 함께 회원가입 요청을 보냅니다. 넘어오는 데이터는 아래와 같습니다.
```
{
"email": "samcomo@gmail.com",
"nickname" : "삼코모",
"phone": "010-1234-5678",
"password" : "123"
}
```
이에 추가적으로 서버에서는 회원의 권한과 접속상태, 생성일자/수정일자 정보를 초기화하여 DB 에 저장합니다.
저장 후 다시 클라이언트로 응답을 보냅니다.
```
{
"memberId": 1,
"memberInfo": {
"email": "samcomo@gmail.com",
"nickname": "삼코모",
"profileImageUrl": "기본이미지 url",
"phone": "010-1234-5678"
},
"status": "ACTIVE",
"role": "MEMBER",
"createdAt": "2024-03-03T00:25:35.196872",
"updatedAt": "2024-03-03T00:25:35.196893"
}
```
<br/>
[서버 플로우]
**-데이터 검증-**
클라이언트에서 요청이 오면 우선적으로 각 데이터 자체의 유효성 검정이 필요합니다. 이 부분은 다른 pr 로 올릴 예정입니다.
**-회원중복 검증-**
데이터 검증이 통과되면 회원 중복 검증이 진행됩니다. email 혹은 nickname 이 기존의 회원과 겹치면 MemberException 이 발생합니다.
**-데이터 가공-**
클라이언트에서 받은 데이터는 서버에서 가공되어 DB 에 …
=> [Feature/register] 회원가입 구현

src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java
- MemberController 테스트 시 발생하는 에러 해결
close #24 
<br/>
<br/>
```java
// error summary
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'jpaAuditingHandler': 
Cannot resolve reference to bean 'jpaMappingContext' while setting constructor argument
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'jpaMappingContext': 
JPA metamodel must not be empty
Caused by: java.lang.IllegalArgumentException: 
JPA metamodel must not be empty
```
<br/>
먼저 공식문서를 찾아보니 `MappingContext` 는 엔티티 간의 연결정보를 매핑하는 인터페이스고, `jpaMappingContext` 는 jpa 엔티티의 연결정보를 매핑하는 구현체임을 알 수 있었다.
위 에러메시지를 다시 보니 에러상황을 대충 추측할 수 있었다.
`jpaAuditingHandler` 빈을 등록하던 도중 `jpaMappingContext` 때문에 에러가 발생했고, `jpaMappingContext` 빈 또한 jpa 엔티티 연결정보가 없어서 …
=> hotfix: jpa metadata empty 에러

build.gradle, src/main/java/com/samcomo/dbz/DbzApplication.java, src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java, src/main/java/com/samcomo/dbz/global/redis/RedisCacheConfig.java, src/main/java/com/samcomo/dbz/global/redis/RedisConfiguration.java, src/main/java/com/samcomo/dbz/report/controller/ReportController.java, src/main/java/com/samcomo/dbz/report/model/dto/CustomPageable.java, src/main/java/com/samcomo/dbz/report/model/dto/CustomSlice.java, src/main/java/com/samcomo/dbz/report/model/dto/ReportList.java, src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java, src/main/java/com/samcomo/dbz/report/service/ReportService.java, src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java, src/main/resources/application-dev.yml, src/main/resources/sql/reportDumy.sql, src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
> getReportList() 메소드에서 쿼리 게시글 리스트를 조회할 때 성능이 좋지 못함을 발견
> API 호출시 30초 소요
기존 offset 방식에서 cursor 방식으로 변경했습니다.
cursor 방식을 사용함으로 기존에 불필요하게 동작 하던 읽기 동작을 하지 않게 되어서 데이터가 많을 수록 눈에 띄는 성능 개선을 확인할 수 있었습니다. 
✅ [노션 정리](https://steadfast-whippet-4c2.notion.site/Query-49713da6a060488b91b50d034bc11fd0)
<br/>
[Spring Data Redis Docs](https://docs.spring.io/spring-data/redis/reference/redis.html)
[Cursor based Pagination](https://velog.io/@znftm97/%EC%BB%A4%EC%84%9C-%EA%B8%B0%EB%B0%98-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%84%A4%EC%9D%B4%EC%85%98Cursor-based-Pagination%EC%9D%B4%EB%9E%80-Querydsl%EB%A1%9C-%EA%B5%AC%ED%98%84%EA%B9%8C%EC%A7%80-so3v8mi2#span-stylecolord9730d7-2-%EC%8B%A4%ED%96%89%EA%B3%84%ED%9A%8D-%ED%99%95%EC%9D%B8---%EC%9D%B8%EB%8D%B1%EC%8A%A4%EA%B0%80-%EC%97%86%EC%9D%84-%EB%95%8Cspan)
<br/>
=> refactor: 게시글 리스트 조회 메소드 성능 개선

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java, src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java, src/main/java/com/samcomo/dbz/global/redis/aop/DistributedLockAop.java, src/main/java/com/samcomo/dbz/report/controller/ReportController.java, src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java, src/main/java/com/samcomo/dbz/report/model/dto/ReportList.java, src/main/java/com/samcomo/dbz/report/model/dto/ReportStateDto.java, src/main/java/com/samcomo/dbz/report/model/entity/Report.java, src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java, src/main/java/com/samcomo/dbz/report/service/ReportService.java, src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java, src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java, src/test/java/com/samcomo/dbz/report/service/ReportViewTest.java
<br/>
- 위/경도 값에 primitive type을 사용하면 0.0이 기본으로 설정 되는데, 이렇게 되면 거리를 계산할 때 정확한 값이 나오지 않으므로 각각 null 값으로 받아 처리하기위해 수정했습니다.
- 프론트에서 게시글의 디테일한 정보를 주는 API 를 호출 할 때 요청자가 작성자와 동일한지를 알 수 있도록 ReportDto.Response에 isWriter 를 추가하여 boolean 타입으로 확인할 수 있도록 수정했습니다.
> 프론트에서 작성자일경우와 작성자가 아닐 경우 UI가 다르게 구성되어 판별할 수 있는 값이 필요하다고 요청이 들어와 수정했습니다.
=> [Refactor/report] 위/경도 파라미터 타입 변경(primitive -> wrapper), Response 파라미터 추가

src/main/java/com/samcomo/dbz/global/s3/service/S3Service.java, src/main/java/com/samcomo/dbz/report/model/entity/ReportImage.java, src/main/java/com/samcomo/dbz/report/model/repository/ReportImageRepository.java, src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
ReportImage에 대한 데이터를 먼저 삭제해야 Report 데이터를 삭제할 수 있습니다. 
Report 의 ID 값을 ReportImage가 관리하고 있기 때문에 선행되어야 할 동작입니다.
이전 코드에서는 ReportImage 삭제를 하는 코드가 수정하면서 지워져서 삭제가 불가능했기 때문에 삭제 메소드를 추가했습니다.
<수정 후>
RepotImage삭제 -> Report 삭제
=> [Hotfix/Report] 게시글 삭제 불가 해결

src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java, src/main/java/com/samcomo/dbz/member/jwt/filter/JwtFilter.java, src/main/java/com/samcomo/dbz/member/jwt/filter/LoginFilter.java, src/main/java/com/samcomo/dbz/member/model/dto/MemberDetails.java, src/main/java/com/samcomo/dbz/report/controller/ReportController.java, src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java, src/main/java/com/samcomo/dbz/report/service/ReportService.java, src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java, src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java, src/test/java/com/samcomo/dbz/report/service/ReportViewTest.java
기존 jwt 에 담기는 정보 중 식별키로 이용한 컬럼은 `email` 이었습니다.
String 값인 이메일 정보로 DB 를 조회하는 것보다 Long 값인 memberId 로 조회하는 것이 효율적이라고 판단하였습니다.
따라서 email 을 페이로드에서 제외하고, id 값을 추가하였습니다.
<br/>
- JwtUtil.java
```java
public String createToken(TokenType tokenType, String id, String role, Long expiredMs) {
return Jwts.builder()
.subject(tokenType.getKey())
.claim(ID_KEY, id)
.claim(ROLE_KEY, role)
.issuedAt(new Date(System.currentTimeMillis()))
.expiration(new Date(System.currentTimeMillis() + expiredMs))
.signWith(secretKey)
.compact();
}
```
로그인 성공 시 jwt 를 생성하는 메서드가 호출되며 이 정보는 헤더에 담겨 반환됩니다.
회원은 앞으로 api 를 요청할 때마다 이 jwt 를 가지고 JwtFilter 에서 인가 과정을 거칩니다.
<br/>
- JwtFilter.java
```java
@Override
protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws …
```
=> [Refactor/member] jwt 토큰 페이로드 정보 변경

src/main/java/com/samcomo/dbz/report/controller/ReportController.java, src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java, src/test/java/com/samcomo/dbz/report/controller/ReportControllerTest.java, src/test/java/com/samcomo/dbz/utils/WithMemberSecurityContextFactory.java, src/test/java/com/samcomo/dbz/utils/annotation/WithMockMember.java
테스트 시 인가처리를 위해 기존에는 아래 어노테이션을 사용했습니다.
```java
@Test
@WithMockUser(username = "test@gmail.com", roles = {"MEMBER"})
void test() ...
```
컨트롤러 단에서 memberDetails 의 id 정보를 가져오기 위해서는 username, roles 가 아닌 id, role 키값을 가진 정보가 필요합니다.  
따라서 커스텀 어노테이션을 구현했습니다.
```java
@Test
@WithMockMember
void test() ...
```
기존 어노테이션보다 훨씬 간결하고, 테스트 코드에 집중할 수 있는 장점과 필요한 정보를 담은 MemberDetails 를 사용할 수 있다는 장점이 있습니다.
<br/>
member 의 마이페이지 조회하는 테스트코드를 참고해서 테스트 작성 시 구현된 어노테이션을 사용해주세요.
report controller 에서 현재는 사라진 memberService 의 메서드 관련 부분은 삭제했습니다!
=> [Feature/member] WithMockMember 어노테이션 구현

src/main/java/com/samcomo/dbz/chat/config/WebSocketConfig.java, src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java, src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java, src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
기존 STOMP 프로토콜을 이용하여 WebSocket 연결시 아무런 검증 로직이 없었습니다.  
로직을 추가하여 Client측에서 WebSocket 을 연결전에 jwt 토큰을 header에 추가해서 검증과정을 거쳐야 웹소켓 연결이 시작됩니다.
JWT토큰이 정상적으로 인증통과가 되면
SpringContext에 해당 JWT토큰에 관한 Authentication이 추가됩니다.
- JWT String 토큰을 검증하는 로직 추가
- WebSocket 연결전 JwtToken 검증로직추가
- SpringSecurity : API주소별 HTTP 프로토콜 필터링 추가
- WebSocketConfig 의 메소드 주석추가
- validateAccessToken : JwtUtil의 메소드 수정
```
// ACCESS TOKEN 가져오기
String accessToken = accessor.getFirstNativeHeader(ACCESS_TOKEN.getKey());
```
로  변경되었기 때문에
프론트에서 JWT토큰값을 보낼때 Header값을 다음과 같이 코드를 변경해야합니다. 
```
const stompClient = new Client({
webSocketFactory: () => new SockJS('/ws'),
connectHeaders: {
"Access-Token": qwehfwqejkhfkjwh12e11l1j2  // 임시 회원의 JWT토큰입니다. 
},
// 생략: onConnect, onStompError 등의 콜백 함수 구현
});
```
- WebSocketConfig 및 JwtUtil에서는 …
=> [FEATURE/CHAT] WebSocket 연결시 JWT 검증 로직 추가

src/main/java/com/samcomo/dbz/chat/config/WebSocketConfig.java, src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java, src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java, src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java, src/main/java/com/samcomo/dbz/member/jwt/filter/AccessTokenFilter.java, src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java, src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLogoutFilter.java, src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java, src/main/java/com/samcomo/dbz/member/model/repository/RefreshTokenRepository.java
spring security 에서 기본적으로 제공하는 LogoutFilter 도 있지만, 우리 프로젝트 상황에 맞게 커스텀하기 위해 해당 필터가 상속 받는 클래스 GenericFilterBean 를 직접 상속받아 구현했습니다.
CustomLogoutFilter 의 동작 방식은 아래와 같습니다.
```
1. 로그아웃을 위해 클라이언트가 "/member/logout" 으로 요청합니다.
2. 필터를 쭉 돌다가 제가 등록한 CustomLogoutFilter 에 도착합니다.
3. 해당 요청이 post 요청인지, uri 는 "/member/logout" 가 맞는지 검증합니다.
4-1. 만약 일치하지 않으면 로그아웃 요청이 아님을 인지하고 다음 필터로 넘어갑니다.
4-2. 만약 일치하면 로그아웃을 계속 진행합니다.
5. 해당 사용자의 쿠키에 담긴 refreshToken 을 가져옵니다.
6. refreshToken 이 유효한 값인지 검증합니다.
7-1. 유효하지 않다면 BadRequest(유효한 값이 아닙니다 or 이미 로그아웃된 사용자입니다.)  로 응답합니다.
7-2. 만약 유효하다면 쿠키의 refreshToken 을 null 값으로 할당하고, DB 에서 해당 토큰을 삭제합니다.
8. status 를 OK (200) 으로 응답합니다.
```
로그인 성공 시 헤더에 Access-Token, 쿠키에 Refresh-Token 을 담아 반환했습니다.  
쿠키는 세션에 비해 보안성이 낮기 때문에 js 로 부터 오는 공격인 xss 접근에 취약합니다.
따라서 아래처럼 http only 설정을 통해 js 의 접근을 막았습니다. …
=> [Feature/logout] 필터를 이용한 로그아웃 구현

src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
pr 을 올릴 때마다 기존 커밋이 중복되어 올라오는 문제가 발생했습니다.
아무런 작업을 하지 않고 push 를 하여도 이전 커밋이 같이 올라옵니다.
<br/>
너무 안 좋은 기억은 까먹나봐요...정확히 기억이 나지는 않습니만,
이틀 전 3개 정도의 pr 을 올렸고, 각각의 pr 은 서로 다른 기능 개발이었습니다.
하지만 각각의 pr 을 순차적으로 merge 하는 과정에서 최신상태로 유지되어야 하는 코드가 다른 pr 이 merge 됨에 따라 사라진 듯 합니다.
문제가 되는 develop 브랜치의 내용이 아닌, 현재 로컬에 있는 최신상태의 브랜치를 기준으로 덮어 씌우기 위해 rebase 를 사용하였습니다.
문제는 rebase 대상 브랜치가 develop 이 었고, 이 develop 브랜치에 변경점이 생기면서 git log가 꼬인 것 같습니다.
<br/>
해결방법을 모색하다 rebase 로 커밋의 위치를 변경시키거나 삭제해서 가능하다는 사실을 알았습니다.
배포 직전 단계에서 위험성을 부담하고 rebase 로 해결하기 보다는,
중복 커밋이 발생하는 브랜치를 삭제 후 다시 원격 저장소에서 새로 브랜치를 받아와 작업하는 것이 수월하다고 판단했습니다.
따라서 main, develop, feature 브랜치를 모두 삭제하고 다시 원격 저장소의 브랜치를 가져와 작업합니다.
<br/>
rebase 의 단점은 공용으로 사용하는 브랜치가 잘못하면 다 날라가거나 원치 않는 방향으로 바뀔 수 있기 때문에 조심해서 사용해야 합니다.
이런 위험성을 안고도 rebase 를 사용하는 분들이 많은 이유는 여러개로 분기되는 브랜치의 수많은 …
=> [Fix/Local-Error] 커밋 중복 현상 해결

src/main/java/com/samcomo/dbz/notification/service/NotificationServiceImpl.java
Report를 보낼 때 발생하는 알림에서
보낼 회원이 없는 경우 발생하는 에러를 수정했습니다.
<br/>
=> fix: 알림을 보낼 회원이 없는 경우

src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequest.java, src/main/java/com/samcomo/dbz/member/model/entity/Member.java, src/test/java/com/samcomo/dbz/member/controller/MemberControllerTest.java, src/test/java/com/samcomo/dbz/member/service/impl/MemberServiceImplTest.java
마이페이지에서 회원의 위치정보를 업데이트 할 수 있는 기능이 있습니다.
그리고, 이 위치를 기반으로 거리순 알림이 발생합니다.
그러나, 마이페이지에서 직접 회원 위치정보를 업데이트 하지 않으면 알림을 받지 못합니다.
이러한 문제를 해결하고자 회원가입 시 위치정보를 같이 받도록 수정합니다.
=> [Feat/member] 회원가입 시 회원 위치정보 저장

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java, src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java, src/main/java/com/samcomo/dbz/member/jwt/AuthUtils.java, src/main/java/com/samcomo/dbz/member/jwt/CookieUtil.java, src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java, src/main/java/com/samcomo/dbz/member/jwt/filter/AccessTokenFilter.java, src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java, src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLogoutFilter.java, src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java, src/main/java/com/samcomo/dbz/member/jwt/filter/handler/LoginSuccessHandler.java, src/main/java/com/samcomo/dbz/member/jwt/filter/handler/Oauth2LoginFailureHandler.java, src/main/java/com/samcomo/dbz/member/model/constants/ParameterKey.java, src/main/java/com/samcomo/dbz/member/model/constants/UriKey.java, src/main/java/com/samcomo/dbz/member/model/dto/oauth2/GoogleResponse.java
구글 서버에서 내려주는 에러가 발생하면 저희 서비스의 커스텀 에러를 발생시킵니다.
```java
SOCIAL_AUTHENTICATION_FAILED(HttpStatus.UNAUTHORIZED, "소셜 로그인 인증에 실패했습니다.")
```
<br/><br/>
```java
ResponseCookie.from(REFRESH_TOKEN.getKey(), null)
.path("/")
.maxAge(0)
.sameSite(SAME_SITE_CONFIG) // 추가됨 ("None")
.httpOnly(true)
.secure(true)
.build());
```
<br/><br/>
```java
private static final String ID_KEY = "id";
private static final String EMAIL_KEY = "email";
ID("id"),
EMAIL("email")
```
여러 클래스에서 자주 사용하는 파라미터는 매번 클래스마다 호출하지 않고, enum 으로 분리하여 호출합니다.
=> [Feature/member] 소셜 로그인 실패 핸들러 추가

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java, src/main/java/com/samcomo/dbz/member/jwt/filter/handler/Oauth2LoginFailureHandler.java
```
2024-04-01T14:26:59.554Z ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 0 of method setFilterChains in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' that could not be found.
```
환경변수값을 현재 서버에서 접속할수없어 임시 주석처리하였습니다.
=> [Bug] 임시 서버에서 AuthO 로직 주석처리

src/main/java/com/samcomo/dbz/report/controller/ReportController.java, src/main/java/com/samcomo/dbz/report/model/dto/ReportWithProfile.java, src/main/java/com/samcomo/dbz/report/model/dto/WriterProfile.java, src/main/java/com/samcomo/dbz/report/service/ReportService.java, src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java, src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
<br/>
> 프론트엔드 파트에서 게시글의 세부정보 조회 시 작성자의 프로필정보(ID, image, nickname)를 함께 넘겨줄 수 있도록 수정 요구
- "ReportWithProfile" DTO 객체에 "WriterProfile" 객체를 담아 반환하도록 수정
- 다음과 같이 "writerProfile"에 nickname, profileImageUrl, id 값을 담아 반환
```
"writerProfile" : {
"nickname": "user1",
"profileImageUrl": "defaultImageUrl.jpg",
"id": 3
}
```
=> refactor : 게시글 세부정보 전달 시 작성자의 프로필정보를 함께 반환하도록 수정

src/main/java/com/samcomo/dbz/chat/model/dto/ChatRoomDto.java, src/main/java/com/samcomo/dbz/chat/model/dto/Participant.java, src/main/java/com/samcomo/dbz/chat/service/impl/ChatRoomServiceImpl.java, src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java, src/main/java/com/samcomo/dbz/report/model/dto/ReportWithProfile.java, src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
<br/>
- ChatRoomDto에 ParticipantList 추가하여 채팅 참여자들의 id, 프로필 이미지 URL, 닉네임을 담을 수 있도록 수정
``` java
participantList: [
participant: {
id: 1, // 참가자의 ID
nickname: 니네임1, // 참가자의 닉네임
profileImageUrl: http://www.imageUrl.com, // 참가자의 프로필 이미지 URL
partner: false // 대화 상대인지 판단 => false : 요청자일 때, true : 상대방일 때
},
participant: {
id: 2,
nickname: 니네임2,
profileImageUrl: http://www.imageUrl.com,
partner: true
}
]
```
=> [Refactor] chatRoomDto 필드 수정

src/main/java/com/samcomo/dbz/chat/service/impl/ChatRoomServiceImpl.java
<br/>
String -> Long 
문자열을 Long 타입으로 변형하는 부분에서 NumberFormatException 발생
[원인]
- memberIdList의 값이 문자열로 넘어오는데 "4,4" 이런 방식으로 넘어오면서 Long 타입으로 변환이 안되었던 것이 문제점
- split()을 사용하여 하나의 Long타입으로 변환할 수 있도록 수정
=> [Fix] getChatRoomsFromMember() 자료형 오류

src/main/java/com/samcomo/dbz/global/config/CorsMvcConfig.java, src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
CorsMvcConfig.java 파일에서 허용된 출처(origin) 목록 업데이트
- http://localhost:5173만 허용 ->  http://localhost:3000, - http://localhost:5173, https://samcomo.site로 확장
- SecurityConfig.java 파일에서 CORS 설정의 허용된 출처 업데이트
-  http://localhost:5173 허용 -> http://localhost:3000, http://localhost:5173, https://samcomo.site 허용
=> CorsMvcConfigTest: CORS origin 추가
