SamCoMo/DBZ-Backend

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
src/main/java/com/samcomo/dbz/report/controller/ReportController.java
src/main/java/com/samcomo/dbz/report/model/constants/PetType.java
src/main/java/com/samcomo/dbz/report/model/constants/ReportStatus.java
src/main/java/com/samcomo/dbz/report/model/dto/CustomPageable.java
src/main/java/com/samcomo/dbz/report/model/dto/CustomSlice.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportImageDto.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportStateDto.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportSummaryDto.java
src/main/java/com/samcomo/dbz/report/model/entity/Report.java
src/main/java/com/samcomo/dbz/report/model/entity/ReportImage.java
src/main/java/com/samcomo/dbz/report/model/repository/ReportRepository.java
src/main/java/com/samcomo/dbz/report/service/ReportService.java
src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java
src/test/java/com/samcomo/dbz/report/service/ReportViewTest.java

- 누락된 필드 추가
- 불필요한 필드 삭제
- 필드 순서 일정하게 유지하기 위해 순서 변경 (리펙터링을 위함)
- noArgs, allArgs 어노테이션 protected 권한으로 제한 (리펙터링을 위함)
- 로그인된 회원 정보 가져오는 방법 수정
- member email 이 아닌 member 자체로 DB 조회하는 방식으로 변경
- 각종 컨벤션 (띄어쓰기, 엔터 등)
<br/>
@JuJaeng2 
코드 땡겨와서 확인 한 번 부탁드려요!! 스프링 내에서 테스트는 모두 통과했습니다.
포스트맨에서 돌렸을 때 다른 api 는 상관없는데,
실제 이미지 관련 요청을 하면 에러가 나는데 이건 이미지 경로 때문인 것 같아요...!
// TODO 로 언급해 놓았으니 확인 부탁드립니다.
- 게시글 삭제
- 게시글 수정
```
{
"errorCode": "AWS_SDK_ERROR",
"errorMessage": "AWS S3 SDK 에러가 발생하여 정보를 처리할 수 없습니다."
}
```
<br/>
- 리스트 조회
- 게시글 검색

[Refactor/dto and entity] 전체적인 Dto, Entity 수정 & 로그인 정보 가져오는 방법 수정

---

src/main/resources/application.yml

deploy : 배포 - V1.1

---

.github/workflows/deployment.yml

deploy : 배포 테스트1

---

src/main/resources/application-dev.yml
src/main/resources/application.yml

fix: yml 파일 복구

---

build.gradle
src/main/java/com/samcomo/dbz/member/controller/MemberController.java
src/main/java/com/samcomo/dbz/member/model/dto/MemberMyInfo.java
src/main/java/com/samcomo/dbz/member/service/MemberService.java
src/main/java/com/samcomo/dbz/member/service/impl/MemberServiceImpl.java

spring-security-test 라이브러리를 사용해서 mock MemberDeatils 를 불러와 사용하려 했으나,
제 로컬에서 해당 라이브러리 import 문제가 있어서 test 부분은 작성하지 못했습니다.
회원 정보를 불러오는 간단한 조회 api 입니다.  
세션에 저장된 MemberDetails 와 일치하는 회원 정보를 가져와 dto 로 반환합니다.
+. 컨트롤러의 authentication 으로 Member 를 가져오는 메서드는 사용할 일이 없어 삭제했습니다.

[Feat/member] 마이페이지 구현

---

src/main/java/com/samcomo/dbz/global/config/MongoConfig.java

refactor: MongoConfig global로 위치 변경, notification repository 추가
현재 notification패키지에서  notification Document가 생성이안되고있습니다. Mongo DB와 연동이 가능하도록 config 파일을 수정했습니다. 
급한 사항이니  바로 머지하겠습니다.

refactor: MongoConfig global로 위치 변경, notification repository 추가

---

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
src/main/java/com/samcomo/dbz/member/controller/MemberController.java
src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
src/main/java/com/samcomo/dbz/member/jwt/filter/AccessTokenFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/LoginFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
src/main/java/com/samcomo/dbz/member/model/dto/RegisterRequestDto.java
src/main/java/com/samcomo/dbz/member/model/entity/RefreshToken.java
src/main/java/com/samcomo/dbz/member/model/repository/RefreshTokenRepository.java

<br/>
<br/>
[auth0 RTR 설명](https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation)
<br/>
RefreshToken 은 현재 MariaDB 에 저장하고 있습니다.
하지만 10분에 한 번 이상 요청이 오고, 해당 요청이 올 때마다 DB 조회와 삭제, 저장 쿼리가 실행됩니다.
따라서 Refresh Token 을 회원 정보를 키값으로 하여 캐시에 저장할 예정입니다.
이 부분은 다른 pr 로 올릴 예정입니다!

[Feature/reissue(RTR)] RTR 방식의 jwt 토큰 재발급 구현

---

build.gradle
src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportSummaryDto.java
src/main/java/com/samcomo/dbz/report/model/repository/ReportBulkRepository.java
src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
src/main/resources/application-dev.yml
src/main/resources/application.yml
src/test/java/com/samcomo/dbz/report/controller/ReportControllerTest.java
src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java

[Refactor/Report] Actuator추가, Response에 wrtierId 추가, 테스트코드 수정

---

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
src/main/java/com/samcomo/dbz/member/controller/MemberController.java
src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
src/main/java/com/samcomo/dbz/member/jwt/filter/AccessTokenFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/FilterMemberExceptionHandler.java
src/main/java/com/samcomo/dbz/member/jwt/filter/JwtFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
src/main/java/com/samcomo/dbz/member/model/dto/MemberDetails.java

주석이 없어도 이해할 수 있도록 나열된 코드를 메서드로 분리했습니다.
```java
// AccessTokenFilter, RefreshTokenFilter 에서 각각 유효성 검증 (코드 중복)
if (refreshToken == null || !jwtUtil.getTokenType(refreshToken).equals(REFRESH_TOKEN.getKey())) {
throw new MemberException(INVALID_REFRESH_TOKEN);
}
```
```java
// 외부에서 토큰 타입에 맞게 유효성 검증 메서드 호출하기
jwtUtil.validateToken(oldRefreshToken, REFRESH_TOKEN);
// jwtUtil 내에서 알아서 유효성 검증
public void validateToken(String token, TokenType tokenType) {
boolean isAccessToken = isAccessTokenString(tokenType);
// 메서드명 가독성 높이기
if (!isValidJwtTokenFormat(token)) {
throw new MemberException(isAccessToken ? INVALID_ACCESS_TOKEN : INVALID_REFRESH_TOKEN);
}
// 생략
}
```
<br/>
기존에 만들어둔 예외 처리 핸들러는 필터에서 발생한 예외의 정보를 가져오지 못합니다.
```java
@RestControllerAdvice
public class GlobalExceptionHandler {
```
기존에 사용한 …

[Refactor/jwt-filter] Filter 클래스의 객체지향적인 코드 설계

---

src/main/java/com/samcomo/dbz/chat/config/WebSocketConfig.java
src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java

validate 로직 중복 -> validateTokenAndTokenType() 메서드를 사용하여서 WebSocket에서 Access Token을 검증합니다.
바로 머지하겠습니다.

refactor: validateTokenAndTokenType 으로 토큰 검사로직 수정

---

src/main/java/com/samcomo/dbz/global/config/CorsMvcConfig.java
src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
src/main/java/com/samcomo/dbz/notification/service/NotificationService.java
src/main/java/com/samcomo/dbz/notification/service/NotificationServiceImpl.java
src/main/java/com/samcomo/dbz/report/model/entity/Report.java
src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java

프론트와 테스트 중 CORS 에러가 발생해서 SecurityConfig에 CORS 설정과 CorsMvcConfig를 추가했습니다.
<br/>
<br/>
<br/>

[Refactor/Security] security cors 설정 추가

---

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java

hotfix: 로그인 오류문제 임시적 CORS "*" 전체경로허용

---

src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java

[Deploy] 배포 V2.4

---

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java

[Deploy] 배포 V2.5

---

src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java

deploy : 배포 V2.6

---

src/main/java/com/samcomo/dbz/report/controller/ReportController.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
src/main/java/com/samcomo/dbz/report/service/ReportService.java
src/main/java/com/samcomo/dbz/report/service/impl/ReportServiceImpl.java
src/test/java/com/samcomo/dbz/report/controller/ReportControllerTest.java
src/test/java/com/samcomo/dbz/report/service/ReportServiceTest.java

[Deploy] 배포 V2.7

---

src/main/java/com/samcomo/dbz/report/controller/ReportController.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java

<br/>
기존 방법을 사요하면 프론트 쪽에서 두가지 타입에 대한 요청을 각각 보내야 하는 번거로움이 발생했습니다. 
한 번의 요청으로 처리할 수 있도록 @ModelAttribute를 사용하여 파라미터를 객체에 바인딩 할 수 있도록 수정했습니다.
**[기존]**
@RequestPart를 사용하여 두가지 Content-Type(application/json, multipart/form-data)을 사용
**[수정 후]**
@ModelAttribute를 사용하여 ReportDto.Form을 사용하여 파라미터들을 바인딩 할 수 있도록 수정
<br/>
<br/>

[Deploy] getReportList 파라미터 바인딩 수정

---

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
src/main/java/com/samcomo/dbz/member/jwt/AuthUtils.java
src/main/java/com/samcomo/dbz/member/jwt/CookieUtil.java
src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLogoutFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java

쿠키가 담기는 로직을 수정하기 위해선 각각의 필터 안에서 모두 수정해야 하는 문제가 있었습니다.
유지보수를 생각하여 쿠키를 생성하거나 삭제는 로직을 따로 util 로 빼서 구현했습니다.

[Refactor/member] 필터 리펙터링 및 쿠키관리용 util 구현

---

src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java

test: access 1분으로 설정 [reissue 태스트용]

---

src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java

refresh 만료시간 1분으로 설정하여 테스트할게요!

test: refresh 1분으로 설정

---

src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java

[Test/reissue] 액세스, 리프레시 토큰 만료 테스트 완료

---

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java
src/main/java/com/samcomo/dbz/global/exception/ErrorCode.java
src/main/java/com/samcomo/dbz/member/jwt/AuthUtils.java
src/main/java/com/samcomo/dbz/member/jwt/CookieUtil.java
src/main/java/com/samcomo/dbz/member/jwt/JwtUtil.java
src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLoginFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/CustomLogoutFilter.java
src/main/java/com/samcomo/dbz/member/jwt/filter/RefreshTokenFilter.java
src/main/java/com/samcomo/dbz/member/model/constants/TokenType.java
src/main/java/com/samcomo/dbz/report/controller/ReportController.java
src/main/java/com/samcomo/dbz/report/model/dto/ReportDto.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

변경내용 확인 부탁드립니다! 문제없으면 동기화 진행할게요.

[Main -> Develop] 동기화

---

src/main/java/com/samcomo/dbz/notification/service/NotificationServiceImpl.java

merge conflict 해결

---

src/main/java/com/samcomo/dbz/global/log/ExecutionTimeLoggingAspect.java
src/main/java/com/samcomo/dbz/global/log/LogMonitoringInvocation.java
src/main/java/com/samcomo/dbz/global/log/MethodInvocationLoggingAspect.java
src/main/java/com/samcomo/dbz/member/model/entity/Member.java
src/main/java/com/samcomo/dbz/pin/dto/PinDto.java
src/main/java/com/samcomo/dbz/pin/dto/PinListDto.java
src/main/java/com/samcomo/dbz/pin/dto/RegisterPinDto.java
src/main/java/com/samcomo/dbz/pin/dto/UpdatePinDto.java
src/main/java/com/samcomo/dbz/pin/model/entity/Pin.java
src/main/java/com/samcomo/dbz/pin/service/impl/PinServiceImpl.java
src/main/java/com/samcomo/dbz/report/controller/ReportController.java

[feature: LogMonitoringInvocation 동시 모니터링 기능 추가]
: 이제 @LogMonitoringInvocation 어노테이션을 메서드 위에 사용하면 메서드에 대한 입력 인자값과 출력 인자값을 확인하며, 메서드가 끝날시 메서드 실행시간이 표시됩니다.
: 주의할점
-> @Async 메소드에는  LogMethodInvocation 로 찍으려고하면 반환값을 이미 반환해버리기 때문에
쓸수없습니다.@LogTimeInvocation 는 사용할수있습니다.
[feature: Pin 로직 foundAt 추가]
: 기존에 삭제되었었던 pin의 foundAt로직이 추가되었습니다.

[Feature] @LogMonitoringInvocation / Pin에서 foundAt 추가

---

src/main/java/com/samcomo/dbz/member/model/dto/oauth2/GoogleResponse.java
src/main/java/com/samcomo/dbz/member/model/dto/oauth2/Oauth2MemberDetails.java
src/main/java/com/samcomo/dbz/member/model/dto/oauth2/Oauth2Response.java

현재 서버에서 오류발생하니 AuthO 관련 기능 주석처리했습니다. 환경변수에서 Auth관련 변수를 추가해주세요

fixed: 임시 서버에서 AuthO 로직 주석처리 3

---

src/main/java/com/samcomo/dbz/pin/controller/PinController.java

Pin 주소변경 상세
// Pin 생성
@PostMapping("/report/pin")
// Pin 수정
@PutMapping("/report/pin/{pinId}")
// Pin 삭제
@DeleteMapping("/report/pin/{pinId}")
// Report 의 Pin List 가져오기
@GetMapping("/report/{reportId}/pin-list")
// Pin 상세정보 가져오기
@GetMapping("/report/pin/{pinId}")

[Refactor/Pin] Pin 주소 /pin -> /report/pin

---

src/main/java/com/samcomo/dbz/global/config/SecurityConfig.java

refactor : websocket 오류 수정
